let arAlimente = [
    "mashed potatoes",
    "meats",
    "beef",
    "wagyu",
    "steak",
    "pork",
    "bacon",
    "ham",
    //
    "poultry",
    "buffalo wing",
    "chicken balls",
    "chicken nuggets",
    "chicken steak",
    "chicken feet",
    "ribs",
    "seafood",
    "fish",
    "salmon",
    "shrimp and prawn",
    "shark",
    //
    "eggs",
    "scrambled egg",
    "sunny side up",
    "omelette",
    "boiled egg",
    "milk",
    "almond milk",
    "soy milk",
    "cow milk",
    "goat milk",
    "onion rings",
    "pasta",
    "lasagna",
    "linguini",
    "ravioli",
    "carbonara",
    "bolognese",
    //
    "spaghetti",
    "spaghetti and meatballs",
    "pancit canton",
    "fettuccine",
    "pudding",
    "pupusa",
    "pie",
    "shepherds pie",
    "apple pie",
    "cream pie",
    "pumpkin pie",
    "key lime pie",
    "peach pie",
    "pizza",
    "pepperoni",
    "hawaiian",
    "margherita",
    "rolls",
    "croquette",
    "egg roll",
    "spring roll",
    "lumpia",
    "burrito",
    "sandwiches",
    "vegetable sandwich",
    "grilled cheese",
    //
    "panini",
    "cheeseburgers",
    "bacon cheeseburger",
    "hamburgers",
    "chicken burger",
    "hot dogs",
    "peanut butter and jam sandwich",
    "submarine sandwich",
    "soup",
    "chowder",
    "clam chowder",
    "corn chowder",
    "sinigang",
    "sushi",
    "stew",
    "taco",
    "tamale",
    "turnover",
    "jamaican patty",
    "waffle",
    "roti canai",
    "asparagus",
    "lomo saltado",
    "biscuits",
    "cookie",
    "cracker",
    "ginger snap",
    "hardtack",
    "abernethy",
    "afghan biscuits",
    "alfajor",
    "almond biscuit",
    "lebkuchen",
    "aachener printen",
    "cornish fairing",
    "speculaas",
    "springerle",
    "kruidnoten",
    "bagel",
    "bialy",
    "croissant",
    "baguette",
    "toast",
    "cabbage",
    "cabbage roll",
    "cake",
    "cheesecake",
    "chocolate cake",
    "carrot cake",
    "strawberry cake",
    "ice-cream cake",
    "vanilla cake",
    "chocolate",
    "pancake",
    "poundcake",
    "chopped liver",
    "cheese",
    "mozzarella",
    "brie",
    "feta",
    "blue cheese",
    "parmesan",
    "cheese stick",
    "congee",
    "donuts",
    "jam",
    "sprinkles",
    "donut holes",
    "dumplings",
    "arepa",
    "fun guo",
    "har gow",
    "momo (food)",
    "pierogi",
    "wonton",
    "fruits",
    //
    "apple",
    "banana",
    "cantaloupe",
    "orange (fruit)",
    "cherry",
    "kiwi",
    "watermelon",
    "avocado",
    "apricot",
    "pear",
    "pineapple",
    "strawberry",
    "french fries",
    "poutine",
    "grains",
    "cereal",
    "corn",
    "popcorn",
    "rice",
    "ice cream",
    "chocolate",
    "vanilla",
    "cookies and cream",
    "mint chocolate",
    "rocky road",
    "biscuit tortoni",
    "blue moon",
    "queso",
    "hokey pokey",
    "moose tracks",
    "tiger tail",
    "strawberry",
    "superman",
    "spumoni",
    "pistachio",
    "moon mist",
    "neapolitan",
    "soda",
    "cola",
    "lemonade",
    "root beer",
    "orange soda",
    "ginger ale",
    "iced tea",
    //
    //
    "saffron",
    "sage",
    "salad",
    "salami",
    "salmon",
    "salsa",
    "salt",
    "sandwich",
    "sauce",
    "sauerkraut",
    "sausage",
    "savory",
    "scallops",
    "scrambled",
    "seaweed",
    "seeds",
    "sesame seed",
    "shallots",
    "sherbet",
    "shish kebabs",
    "shrimp",
    "slaw",
    "slices",
    "smoked",
    "snacks",
    "soda",
    "soda bread",
    "soles",
    "sorbet",
    "sorghum",
    "sorrel",
    "soup",
    "sour",
    "sour cream",
    "soy",
    "soy sauce",
    "soybeans",
    "spaghetti",
    "spareribs",
    "spatula",
    "spices",
    "spicy",
    "spinach",
    "split peas",
    "spoon",
    "pork",
    "sprinkles",
    "sprouts",
    "spuds",
    "squash",
    "squid",
    "steak",
    "stew",
    "stir-fry",
    "stomach",
    "stove",
    "straw",
    "strawberry",
    "string bean",
    "stringy",
    "strudel",
    "sub sandwich",
    "submarine sandwich",
    "succotash",
    "suet",
    "sugar",
    "summer squash",
    "sundae",
    "sunflower",
    "supper",
    "sushi",
    "sustenance",
    "sweets",
    "sweet potato",
    "swiss chard",
    "syrup",
    //
    //
    //
    "cake",
    "calorie",
    "candy",
    "candy apple",
    "cantaloupe",
    "capers",
    "caramel",
    "caramel apple",
    "carbohydrate",
    "carrot",
    "cashew",
    "cassava",
    "casserole",
    "cater",
    "cauliflower",
    "caviar",
    "cayenne pepper",
    "celery",
    "cereal",
    "chard",
    "cheddar",
    "cheese",
    "cheesecake",
    "chef",
    "cherry",
    "chew",
    "chickpeas",
    "chicken",
    "chili",
    "chips",
    "chives",
    "chocolate",
    "chopsticks",
    "chow",
    "chutney",
    "cilantro",
    "cinnamon",
    "citron",
    "citrus",
    "clam",
    "cloves",
    "cobbler",
    "coconut",
    "cod",
    "coffee",
    "coleslaw",
    "collard greens",
    "comestibles",
    "cook",
    "cookbook",
    "cookie",
    "corn",
    "cornflakes",
    "cornmeal",
    "cottage cheese",
    "crab",
    "crackers",
    "cranberry",
    "cream",
    "cream cheese",
    "crepe",
    "crisp",
    "crunch",
    "crust",
    "cucumber",
    "cuisine",
    "cupboard",
    "cupcake",
    "curds",
    "currants",
    "curry",
    "custard",
    //
    //
    "fast",
    "fat",
    "fava beans",
    "feast",
    "fed",
    "feed",
    "fennel",
    "fig",
    "fillet",
    "fire",
    "fish",
    "flan",
    "flax",
    "flour",
    "food",
    "food pyramid",
    "foodstuffs",
    "fork",
    "freezer",
    "French fries",
    "fried",
    "fritter",
    "frosting",
    "fruit",
    "fry",
    "garlic",
    "gastronomy",
    "gelatin",
    "ginger",
    "ginger ale",
    "gingerbread",
    "glasses",
    "Gouda cheese",
    "grain",
    "granola",
    "grape",
    "grapefruit",
    "grated",
    "gravy",
    "green bean",
    "green tea",
    "greens",
    "grub",
    "guacamole",
    "guava",
    "gyro",
    "halibut",
    "ham",
    "hamburger",
    "hash",
    "hazelnut",
    "herbs",
    "honey",
    "honeydew",
    "horseradish",
    "hot",
    "hot dog",
    "hot sauce",
    "hummus",
    "hunger",
    "hungry",
    //
    //
    //
    "ice",
    "ice cream",
    "ice cream cone",
    "iceberg lettuce",
    "iced tea",
    "icing",
    "jackfruit",
    "jalapeño",
    "jam",
    "jelly",
    "jellybeans",
    "jicama",
    "jimmies",
    "Jordan almonds",
    "jug",
    "juice",
    "julienne",
    "junk food",
    "kale",
    "kebab",
    "ketchup",
    "kettle",
    "kettle corn",
    "kidney beans",
    "kitchen",
    "kiwi",
    "knife",
    "kohlrabi",
    "kumquat",
    "ladle",
    "lamb",
    "lard",
    "lasagna",
    "legumes",
    "lemon",
    "lemonade",
    "lentils",
    "lettuce",
    "licorice",
    "lima beans",
    "lime",
    "liver",
    "loaf",
    "lobster",
    "lollipop",
    "loquat",
    "lox",
    "lunch",
    "lunch box",
    "lunchmeat",
    "lychee",
    "macaroni",
    "macaroon",
    "main course",
    "maize",
    "mandarin orange",
    "mango",
    "maple syrup",
    "margarine",
    "marionberry",
    "marmalade",
    "marshmallow",
    "mashed potatoes",
    "mayonnaise",
    "meat",
    "meatball",
    "meatloaf",
    "melon",
    "menu",
    "mescaline",
    "micronutrient",
    "milk",
    "milkshake",
    "millet",
    "mincemeat",
    "minerals",
    "mint",
    "mochi",
    "molasses",
    "mole sauce",
    "mozzarella",
    "muffin",
    "mug",
    "munch",
    "mushroom",
    "mussels",
    "mustard",
    "mustard greens",
    "mutton",
    //
    //
    "napkin",
    "nectar",
    "nectarine",
    "nibble",
    "noodles",
    "nosh",
    "nourish",
    "nourishment",
    "nut",
    "nutmeg",
    "nutrient",
    "nutrition",
    "nutritious",
    "oatmeal",
    "oats",
    "oil",
    "okra",
    "oleo",
    "olive",
    "omelet",
    "omnivore",
    "onion",
    "orange",
    "order",
    "oregano",
    "oven",
    "oyster",

    
]
module.exports = {arAlimente}